---
# Component versions
deploy_monitoring_node_exporter_version: "1.9.0"
deploy_monitoring_promtail_version: "3.4.2"
deploy_monitoring_loki_version: "3.4.2"
deploy_monitoring_prometheus_version: "3.2.1"
deploy_monitoring_grafana_version: "11.6.0"

# Architecture
deploy_monitoring_arch: "amd64"

# Loki
deploy_monitoring_loki_listen_address: "{{ mgmt_ip }}"
deploy_monitoring_loki_http_port: 3100
deploy_monitoring_loki_data_dir: /var/lib/loki
deploy_monitoring_loki_retention_period: 720h  # 30 days

# Prometheus
deploy_monitoring_prometheus_listen_address: "{{ mgmt_ip }}"
deploy_monitoring_prometheus_http_port: 9090
deploy_monitoring_prometheus_data_dir: /var/lib/prometheus
deploy_monitoring_prometheus_retention_period: 30d
deploy_monitoring_prometheus_scrape_interval: 15s

# Promtail
deploy_monitoring_promtail_http_port: 9080
deploy_monitoring_loki_push_url: "http://192.168.50.168:{{ deploy_monitoring_loki_http_port }}/loki/api/v1/push"

# node_exporter
deploy_monitoring_node_exporter_listen_address: "{{ mgmt_ip }}"
deploy_monitoring_node_exporter_port: 9100

# Grafana
deploy_monitoring_grafana_listen_address: "{{ mgmt_ip }}"
deploy_monitoring_grafana_http_port: 3000

# Scrape targets for Prometheus (all nodes)
deploy_monitoring_prometheus_node_targets:
  - address: "192.168.50.168:9100"
    hostname: "mgmt.cloud-4core.local"
  - address: "192.168.50.171:9100"
    hostname: "mgmt.cloud-6core.local"
  - address: "192.168.50.178:9100"
    hostname: "mgmt.cloud-celeron.local"
  - address: "192.168.50.234:9100"
    hostname: "mgmt.cloud-eugene.local"
