---
- name: Converge
  hosts: all
  become: true
  vars:
    # Disable reboot in container testing
    install_packages_reboot: false
    # Don't do dist-upgrade in test to save time
    install_packages_dist_upgrade: false
    # Test with a subset of packages
    install_packages_list:
      - bridge-utils
      - tcpdump
      - vlan
      - python3

  tasks:
    - name: Include install_packages role
      ansible.builtin.include_role:
        name: install_packages
