---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: ubuntu2404-test
    image: docker.io/library/ubuntu:24.04
    pre_build_image: true
    command: sleep infinity
    privileged: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks,timer
      stdout_callback: community.general.dense
  playbooks:
    converge: converge.yml

verifier:
  name: ansible
