---
- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Install Python and dependencies
      ansible.builtin.raw: /bin/bash -c "apt-get update && apt-get install -y python3 python3-apt sudo"
      changed_when: false
