galaxy_info:
  author: Kevin Brown
  description: Example role
  company: Webstack Builders, Inc.
  license: MIT
  min_ansible_version: "2.19"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags: []
dependencies: []
