---
all:
  children:
    controllers:
      hosts:
        mgmt.cloud-4core.local:
    compute:
      hosts:
        mgmt.cloud-6core.local:
        mgmt.cloud-celeron.local:
        mgmt.cloud-eugene.local: