---
driver:
  name: podman

platforms:
  - name: ubuntu2404-vim-test
    image: docker.io/library/ubuntu:24.04
    pre_build_image: true
    command: sleep infinity
    privileged: false

provisioner:
  name: ansible

verifier:
  name: ansible